# Generated by Django 2.0 on 2021-08-02 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210727_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materials',
            name='Material_Code',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='materials',
            name='Material_Descriptions',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='materials',
            name='Material_Location',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='materials',
            name='Maximum_Level',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='materials',
            name='Minimum_Level',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='materials',
            name='Re_order_Level',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='materials',
            name='Unit_of_Measurement',
            field=models.CharField(default=0, max_length=255, null=True),
        ),
    ]
