# Generated by Django 2.0 on 2021-08-02 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210802_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materials',
            name='Maximum_Level',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='materials',
            name='Minimum_Level',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='materials',
            name='Re_order_Level',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='materials',
            name='Unit_of_Measurement',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
