# Generated by Django 2.0 on 2021-08-02 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20210802_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='materials',
            name='Quantity',
            field=models.IntegerField(null=True),
        ),
    ]
