# Generated by Django 2.0 on 2021-08-02 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_materials_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materials',
            name='Material_Code',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='materials',
            name='Material_Descriptions',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
