# Generated by Django 2.0 on 2021-08-03 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20210802_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materials',
            name='Material_Code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='materials',
            name='Material_Descriptions',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='materials',
            name='Maximum_Level',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='materials',
            name='Minimum_Level',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='materials',
            name='Quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='materials',
            name='Re_order_Level',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='materials',
            name='Unit_of_Measurement',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
