# Generated by Django 2.0 on 2021-08-04 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20210803_0710'),
    ]

    operations = [
        migrations.RenameField(
            model_name='materials',
            old_name='Material_Descriptions',
            new_name='Material_Name',
        ),
    ]
