# Generated by Django 2.0 on 2021-08-05 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20210805_0704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='material_code',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.Materials'),
        ),
    ]
