# Generated by Django 2.0 on 2021-08-05 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_transact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transact',
            name='material_code',
        ),
        migrations.DeleteModel(
            name='Transact',
        ),
    ]
