# Generated by Django 2.0 on 2021-08-05 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_transact'),
    ]

    operations = [
        migrations.AddField(
            model_name='transact',
            name='receipt_no',
            field=models.IntegerField(default=0),
        ),
    ]
