# Generated by Django 2.0 on 2021-08-09 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_transact_receipt_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materials',
            name='Material_Code',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
