# Generated by Django 2.0 on 2021-08-09 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_auto_20210809_0615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materials',
            name='Material_Code',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
