# Generated by Django 2.0 on 2021-08-10 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_auto_20210809_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materials',
            name='Material_Code',
            field=models.CharField(max_length=255),
        ),
    ]
