# Generated by Django 2.0 on 2021-08-10 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0026_auto_20210810_0723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materials',
            name='Material_Code',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
